spring:
  profiles:
    active: local
    group:
      local:
        - common

---

logging:
  level:
    com.reservation.ticket: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.sql: debug
    org.hibernate.type: trace

spring:
  config:
    activate:
      on-profile: common

springdoc:
  packages-to-scan: com.reservation.ticket.application
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /api
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

---

spring:
  profiles.active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/concert?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    open-in-view: false
  sql.init.mode: always
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234


---

spring:
  profiles.active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/concert?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    open-in-view: false
  sql.init.mode: always
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
