version: "3.8"
services:
  mysql_local:
    container_name: mysql_local
    build:
      dockerfile: docker/database/Dockerfile
      context: database
    image: futuremaker019/mysql_local
    environment:
      - MYSQL_DATABASE=concert
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./docker/database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    network_mode: host